"""Add User and Rename Scenario to Case

Revision ID: 2d44d4c5a385
Revises: c7e80957818e
Create Date: 2026-01-31 22:20:56.606679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d44d4c5a385'
down_revision: Union[str, Sequence[str], None] = 'c7e80957818e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('landlord_name', sa.String(length=255), nullable=True),
    sa.Column('landlord_email', sa.String(length=255), nullable=True),
    sa.Column('property_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_slug'), 'cases', ['slug'], unique=True)
    op.create_index(op.f('ix_cases_title'), 'cases', ['title'], unique=False)
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_slug'), table_name='scenarios')
    op.drop_table('scenarios')
    op.add_column('outcomes', sa.Column('logic_code', sa.String(), nullable=True))
    op.add_column('outcomes', sa.Column('title', sa.String(), nullable=True))
    op.add_column('outcomes', sa.Column('content', sa.String(), nullable=True))
    op.drop_constraint(None, 'outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'outcomes', 'cases', ['scenario_id'], ['id'])
    op.drop_column('outcomes', 'rights_explanation')
    op.drop_column('outcomes', 'summary')
    op.drop_column('outcomes', 'letter_template')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'cases', ['scenario_id'], ['id'])
    op.add_column('usage_logs', sa.Column('scenario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usage_logs', 'cases', ['scenario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.drop_column('usage_logs', 'scenario_id')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'scenarios', ['scenario_id'], ['id'])
    op.add_column('outcomes', sa.Column('letter_template', sa.TEXT(), nullable=True))
    op.add_column('outcomes', sa.Column('summary', sa.VARCHAR(), nullable=True))
    op.add_column('outcomes', sa.Column('rights_explanation', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'outcomes', type_='foreignkey')
    op.create_foreign_key(None, 'outcomes', 'scenarios', ['scenario_id'], ['id'])
    op.drop_column('outcomes', 'content')
    op.drop_column('outcomes', 'title')
    op.drop_column('outcomes', 'logic_code')
    op.create_table('scenarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_slug'), 'scenarios', ['slug'], unique=1)
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.drop_index(op.f('ix_cases_title'), table_name='cases')
    op.drop_index(op.f('ix_cases_slug'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('users')
    # ### end Alembic commands ###
